Detect all introduced names
equinor/xun pull request #105
Opened 2021-04-12 13:44 UTC by LauraSManns

2021-04-15 09:18 UTC, JensGM commented on xun/functions/util.py
> +                a = {stmt.target.id}
I think for statements can have multiple targets

2021-04-16 07:32 UTC, mrSundvoll requested changes

2021-04-16 07:32 UTC, mrSundvoll commented on xun/functions/util.py
> +        return frozenset(names)
We need to consider the case where the `stmt.target` is a tuple, e.g. `for i,j in d.items():`.

```suggestion
    def names_in_target(target):
        names = set()
        for elt in target.elts:
            if isinstance(elt, ast.Name):
                names.add(elt.id)
            elif isinstance(elt. ast.Tuple):
                names.update(names_in_target(elt)
            else:
                raise TypeError(f'Invalid AST type {type(elt)}')
        return names
        
    if isinstance(stmt, (ast.For, ast.AsyncFor)):
        names = names_in_target(stmt.target)
        add_names_from_body(names, stmt.body)
        return frozenset(names)
```

2021-04-19 11:44 UTC, mrSundvoll approved these changes

2021-04-19 12:52 UTC, JensGM requested changes

2021-04-19 12:52 UTC, JensGM commented on xun/functions/util.py
> +        return frozenset(names)
```suggestion
    if isinstance(stmt, ast.Try):
        names = {stmt_introduced_names(s) for s in stmt.body}
        names |= {stmt_introduced_names(s) for s in handler for handler in stmt.handlers}
        names |= {stmt_introduced_names(s) for s in stmt.orelse}
        names |= {stmt_introduced_names(s) for s in stmt.finalbody}
        return frozenset(names)
```

```suggestion
    if isinstance(stmt, ast.Try):
        return frozenset().union(
            {stmt_introduced_names(s) for s in stmt.body},
            {stmt_introduced_names(s) for s in h for h in stmt.handlers},
            {stmt_introduced_names(s) for s in stmt.orelse},
            {stmt_introduced_names(s) for s in stmt.finalbody},
        )
```

2021-04-19 12:52 UTC, JensGM commented on xun/functions/util.py
> +        return frozenset(names)
```suggestion
    if isinstance(stmt, (ast.While, ast.If)):
        return frozenset(stmt_introduced_names(s) for s in stmt.body)
```

2021-04-19 12:52 UTC, JensGM commented on xun/functions/util.py
> +        return frozenset(names)
```suggestion
        names = frozenset()
        names |= assignment_target_introduced_names(stmt.target)
        names |= {statement_introduced_names(s) for s in stmt.body}
        return names
```

2021-04-19 12:52 UTC, JensGM commented on xun/functions/util.py
> +        return frozenset(names)
```suggestion
    if isinstance(stmt, (ast.With, ast.AsyncWith)):
        names = frozenset()
        names |= {assignment_target_introduced_names(item.optional_vars)
                  for item in stmt.items if item.optional_vars is not None}
        names |= {stmt_introduced_names(s) for s in stmt.body}
        return names
```

2021-04-19 12:52 UTC, JensGM commented on xun/functions/util.py
> +        return frozenset({stmt.target.id})
```suggestion
        return assignment_target_introduced_names(stmt.target)
```

2021-04-19 12:52 UTC, JensGM commented on xun/functions/util.py
> +        return names
```suggestion
```

2021-04-19 13:14 UTC, JensGM commented on xun/functions/util.py
> +        names |= {stmt_introduced_names(s) for s in stmt.body}
```suggestion
        names |= chain(stmt_introduced_names(s) for s in stmt.body)
```

2021-04-19 13:15 UTC, JensGM approved these changes
When tests run, if you rebase I'm happy!

2021-04-20 08:51 UTC, mrSundvoll approved these changes

2021-04-20 08:54 UTC, merged