Froze dicts
equinor/xun pull request #124
Opened 2021-05-21 08:11 UTC by IvanKolesarEquinor

2021-05-27 10:32 UTC, JensGM requested changes

2021-05-27 13:12 UTC, IvanKolesarEquinor commented on xun/functions/util.py
> +            k: immutables.Map(it)
done

2021-05-27 13:13 UTC, IvanKolesarEquinor commented on xun/functions/util.py
> +    return items
Done, thanks for suggestion.

2021-05-28 09:06 UTC, JensGM approved these changes

2021-05-28 13:38 UTC, merged