WIP Accept function without target in with constants statement
equinor/xun pull request #33
Opened 2020-09-18 10:19 UTC by mrSundvoll

2020-09-22 18:20 UTC, mrSundvoll reviewed
Really simple fix that allows for simple expressions in with constants statements. Is this a too simple solution @JensGM ?

2020-09-22 18:34 UTC, mrSundvoll reviewed
Really simple fix that allows for simple expressions in with constants statements. Is this a too simple solution @JensGM ?

2020-09-23 12:40 UTC, JensGM requested changes
I think both commits should be a single one. Ideally, all tests should pass for all commits in the history

2020-09-23 12:40 UTC, JensGM commented on xun/tests/test_transformations.py
> +    assert result == 1
Missing new line at end of file

2020-09-23 12:40 UTC, JensGM commented on xun/functions/util.py
>      )
It's possible to check all types at once. Also, I think the bug here was using `ast.Expression` in the first place, I _think_ it should've been `ast.Expr` all along

```suggestion
    return all(isinstance(node, (ast.Assign, ast.Expr)) for node in node.body)
```

2020-09-23 14:04 UTC, JensGM approved these changes
Looks good!

2020-09-24 06:24 UTC, merged