Allow compilation of empty xun function
equinor/xun pull request #64
Opened 2021-01-29 09:35 UTC by IvanKolesarEquinor

2021-02-05 13:50 UTC, JensGM requested changes

2021-02-05 13:50 UTC, JensGM commented on xun/functions/function_description.py
> +
Commented code

2021-02-15 10:34 UTC, IvanKolesarEquinor commented on xun/functions/function_description.py
> +
Removed

2021-02-15 10:38 UTC, JensGM approved these changes
Looks good!

2021-02-15 10:38 UTC, merged