Unpack subscripted function
equinor/xun pull request #97
Opened 2021-03-25 20:12 UTC by mrSundvoll

2021-03-29 06:51 UTC, mrSundvoll commented on xun/functions/graph.py
> +        return output
@JensGM is there a better way to share only this one function between the two successive classes?

2021-03-29 14:13 UTC, JensGM commented on xun/functions/graph.py
> +class Unpackable:
Make CallNodes unpackable instead :D

2021-04-08 10:04 UTC, JensGM requested changes
Do magic

2021-04-08 15:02 UTC, JensGM approved these changes
Brilliant

2021-04-09 06:32 UTC, merged